CRITICAL - 2022-02-09 00:23:40 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\e-potensi\system\Database\Config.php(87): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\e-potensi\system\Model.php(111): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(12): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-09 00:24:10 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\e-potensi\system\Database\Config.php(87): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\e-potensi\system\Model.php(111): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(12): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-09 00:24:23 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\e-potensi\system\Database\Config.php(87): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\e-potensi\system\Model.php(111): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(12): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-09 00:24:36 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\e-potensi\system\Database\Config.php(87): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\e-potensi\system\Model.php(111): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(12): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-09 00:25:18 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\e-potensi\system\Database\Config.php(87): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\e-potensi\system\Model.php(111): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(12): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-09 00:25:31 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\e-potensi\system\Database\Config.php(87): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\e-potensi\system\Model.php(111): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(12): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-09 00:44:28 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\e-potensi\system\Database\Config.php(87): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\e-potensi\system\Model.php(111): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(12): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-09 00:44:58 --> You have not selected a database type to connect to.
#0 C:\xampp\htdocs\e-potensi\system\Database\Config.php(87): CodeIgniter\Database\Database->load(Array, 'default')
#1 C:\xampp\htdocs\e-potensi\system\Model.php(111): CodeIgniter\Database\Config::connect('default')
#2 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(12): CodeIgniter\Model->__construct()
#3 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(908): App\Controllers\Auth->__construct()
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(422): CodeIgniter\CodeIgniter->createController()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-09 00:45:12 --> Cannot declare class CodeIgniter\Database\MySQLi\Connection, because the name is already in use
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2022-02-09 00:46:44 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-09 00:46:44 --> Unable to connect to the database.
#0 C:\xampp\htdocs\e-potensi\system\Database\BaseConnection.php(618): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\e-potensi\system\Database\BaseBuilder.php(2035): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\e-potensi\system\Model.php(836): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(113): CodeIgniter\Model->__call('getWhere', Array)
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-09 00:47:35 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-09 00:47:35 --> Unable to connect to the database.
#0 C:\xampp\htdocs\e-potensi\system\Database\BaseConnection.php(599): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\e-potensi\system\Database\BaseBuilder.php(2035): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\e-potensi\system\Model.php(836): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(113): CodeIgniter\Model->__call('getWhere', Array)
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-09 00:47:55 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-09 00:47:55 --> Unable to connect to the database.
#0 C:\xampp\htdocs\e-potensi\system\Database\BaseConnection.php(599): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\e-potensi\system\Database\BaseBuilder.php(2035): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\e-potensi\system\Model.php(836): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(113): CodeIgniter\Model->__call('getWhere', Array)
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-09 00:50:49 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-09 00:50:49 --> Unable to connect to the database.
#0 C:\xampp\htdocs\e-potensi\system\Database\BaseConnection.php(599): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\e-potensi\system\Database\BaseBuilder.php(2035): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\e-potensi\system\Model.php(836): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(113): CodeIgniter\Model->__call('getWhere', Array)
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-09 01:51:31 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-09 01:51:31 --> Unable to connect to the database.
#0 C:\xampp\htdocs\e-potensi\system\Database\BaseConnection.php(599): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\e-potensi\system\Database\BaseBuilder.php(2035): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\e-potensi\system\Model.php(836): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(113): CodeIgniter\Model->__call('getWhere', Array)
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-09 01:51:48 --> Error connecting to the database: php_network_getaddresses: getaddrinfo failed: No such host is known. 
CRITICAL - 2022-02-09 01:51:48 --> Unable to connect to the database.
#0 C:\xampp\htdocs\e-potensi\system\Database\BaseConnection.php(599): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\e-potensi\system\Database\BaseBuilder.php(2035): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\e-potensi\system\Model.php(836): CodeIgniter\Database\BaseBuilder->getWhere(Array)
#3 C:\xampp\htdocs\e-potensi\app\Controllers\Auth.php(113): CodeIgniter\Model->__call('getWhere', Array)
#4 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(936): App\Controllers\Auth->login()
#5 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(432): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#6 C:\xampp\htdocs\e-potensi\system\CodeIgniter.php(333): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\e-potensi\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 {main}
